# Generated by Django 4.2.4 on 2023-10-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='food/images/')),
                ('description', models.CharField(max_length=250)),
                ('calories', models.IntegerField()),
            ],
        ),
    ]
